# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brian Ngan
email: brianngan92@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brian Ngan. Writing on product management, design and things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brianngan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brian
github_username:  brianngan

# Build settings
markdown: kramdown
# theme: minima

tag_page_layout: tag_page
tag_page_dir: tag

require:
  bootstrap-sass

plugins:
- bootstrap-sass
- jekyll-feed
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate
- jekyll-include-cache
- liquid_reading_time
- nokogiri
- jekyll-watch
- jemoji
- jekyll-tagging

permalink: /:categories/:title:output_ext
paginate_path: "/blog/page:num/"

paginate: 5

sass:
  sass_dir: _sass
  style: compressed

bootstrap:
  assets: true

incremental: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # - Gemfile
  # - Gemfile.lock
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  # - .forestry
  # - _sass/bootstrap-4.0.0
  # - _posts
  # - uploads